### ISSUE TITLE
[Feature Request] Sync packages-index with ruyisdk/support-matrix

### ISSUE THREAD

**Issue by KevinMX** [ruyisdk/packages-index#6]
We have implemented metadata for tested OS & board combo in ruyisdk/support-matrix.

Currently we have things like:

```yaml
product: BananaPi BPI-F3
cpu: Key Stone K1
cpu_core: SpacemiT X60
```

```yaml
sys: bianbu
sys_ver: 2.0rc1
sys_var: null

status: basic
last_update: 2024-09-20
```

See: https://github.com/ruyisdk/support-matrix/blob/main/assets/metadata.yml

```yaml
# Definations for README metadata
definitions:
  status_enum:
    type: string
    enum: &STATUS_ENUM
      - none
      - wip
      - cft
      - cfh
      - cfi
      - partial
      - basic
      - good

# General info
sys: string        # System name, should be one of key in linux/bsd/rtos/others
sys_ver: string    # System version
sys_var: string?   # System variant, be like: desktop/minimal/etc

# Doc info
status: *STATUS_ENUM
last_updated: timestamp   # Last update

# Definition for board metadata
product: string     # Product name
cpu: string         # CPU model
cpu_core: string   # CPU core
```

As some board images in this repo are already out of date, maybe we can consider some sort of auto sync mechanism/CI, which could keep the board images metadata up to date. 

Which of course, if they're also up to date in the test reports of support-matrix repo. I'll keep watching on support-matrix repo and try to keep them updated.
